/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_bridgeencryption_free: (a: number, b: number) => void;
export const __wbg_idkitproof_free: (a: number, b: number) => void;
export const __wbg_idkitrequest_free: (a: number, b: number) => void;
export const __wbg_session_free: (a: number, b: number) => void;
export const base64Decode: (a: number, b: number, c: number) => void;
export const base64Encode: (a: number, b: number, c: number) => void;
export const bridgeencryption_decrypt: (a: number, b: number, c: number, d: number) => void;
export const bridgeencryption_encrypt: (a: number, b: number, c: number, d: number) => void;
export const bridgeencryption_keyBase64: (a: number, b: number) => void;
export const bridgeencryption_new: (a: number) => void;
export const bridgeencryption_nonceBase64: (a: number, b: number) => void;
export const hashSignal: (a: number, b: number, c: number) => void;
export const idkitproof_new: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => void;
export const idkitproof_toJSON: (a: number, b: number) => void;
export const idkitrequest_getSignalBytes: (a: number, b: number) => void;
export const idkitrequest_new: (a: number, b: number, c: number, d: number) => void;
export const idkitrequest_toJSON: (a: number, b: number) => void;
export const idkitrequest_withBytes: (a: number, b: number, c: number, d: number) => void;
export const session_connectUrl: (a: number, b: number) => void;
export const session_new: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => number;
export const session_pollForStatus: (a: number) => number;
export const session_requestId: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_449: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_448: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_393: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_392: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_1027: (a: number, b: number, c: number, d: number) => void;
export const __wbindgen_export: (a: number, b: number) => number;
export const __wbindgen_export2: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export3: (a: number) => void;
export const __wbindgen_add_to_stack_pointer: (a: number) => number;
export const __wbindgen_export4: (a: number, b: number, c: number) => void;
