import org.gradle.api.publish.maven.tasks.PublishToMavenLocal
import org.gradle.api.publish.maven.tasks.PublishToMavenRepository

plugins {
    id("org.jetbrains.kotlin.multiplatform")
    id("org.jetbrains.kotlin.plugin.serialization")
    id("com.android.library")
    id("com.vanniktech.maven.publish.base") version "0.34.0"
}

val libraryGroup = "com.worldcoin"
val libraryArtifactId = "idkit"

// Allow callers to exercise the Maven publication with an explicit artifact version.
val libraryVersion = System.getenv("PKG_VERSION")?.takeIf { it.isNotBlank() }
    ?: project.version.toString().takeIf { it.isNotBlank() && it != "unspecified" }
    ?: throw GradleException("Could not find version in kotlin/gradle.properties")

val enableMavenCentralPublishing = providers.gradleProperty("idkit.publish.mavenCentral")
    .map(String::toBoolean)
    .orElse(false)

group = libraryGroup
version = libraryVersion

// Derived from this module's location (kotlin/idkit) so it stays correct when
// the module is included from another build (the example apps remap projectDir).
val repoRoot: File = projectDir.parentFile.parentFile

// commonMain has no BuildConfig; generate the package version constant instead.
val generateVersionFile by tasks.registering {
    val outDir = layout.buildDirectory.dir("generated/idkitVersion/kotlin")
    inputs.property("version", libraryVersion)
    outputs.dir(outDir)
    doLast {
        val file = outDir.get()
            .file("com/worldcoin/idkit/IDKitVersion.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            // Generated by kotlin/idkit/build.gradle.kts — do not edit.
            package com.worldcoin.idkit

            internal const val IDKIT_PACKAGE_VERSION: String = "$libraryVersion"
            """.trimIndent() + "\n",
        )
    }
}

// Native artifacts produced by scripts/build-kotlin.sh, consumed at build time.
val requiredNativeAbis = listOf("arm64-v8a", "armeabi-v7a", "x86", "x86_64")
val iosRustTriples = listOf("aarch64-apple-ios", "aarch64-apple-ios-sim", "x86_64-apple-ios")

// Apple targets can only build on macOS hosts (kotlin.native.ignoreDisabledTargets
// disables them elsewhere), so the iOS static libs are only required there.
val hostIsMac = System.getProperty("os.name").startsWith("Mac")

// CI rehearses the full multi-target publication to Maven Local on macOS hosts
// that cannot cross-build the Android .so files. The flag only relaxes the
// Android native-library check for LOCAL publishing; remote publishing rejects
// it outright (see requireAppleHostForRemotePublish).
val rehearsalAllowMissingAndroidNativeLibs = providers
    .gradleProperty("idkit.rehearsal.allowMissingAndroidNativeLibs")
    .map(String::toBoolean)
    .orElse(false)

val verifyKmpNativeLibraries by tasks.registering {
    group = "verification"
    description = "Verifies that publishing includes the Rust native libraries for every enabled target."

    doLast {
        val missing = buildList {
            if (!rehearsalAllowMissingAndroidNativeLibs.get()) {
                requiredNativeAbis.forEach { abi ->
                    val lib = layout.projectDirectory
                        .file("src/androidMain/jniLibs/$abi/libidkit_kmp.so").asFile
                    if (!lib.isFile || lib.length() == 0L) add("- android/$abi: $lib")
                }
            }
            if (hostIsMac) {
                iosRustTriples.forEach { triple ->
                    val lib = repoRoot.resolve("target/$triple/release/libidkit_kmp.a")
                    if (!lib.isFile || lib.length() == 0L) add("- ios/$triple: $lib")
                }
            }
        }
        if (missing.isNotEmpty()) {
            throw GradleException(
                "Missing native libraries required for publishing:\n" +
                    missing.joinToString("\n") + "\n" +
                    "Run `bash scripts/build-kotlin.sh` from the repository root before publishing.",
            )
        }
    }
}

// Publishing to a remote repository from a non-macOS host would upload root
// Gradle module metadata without the iOS variants — Android consumers would
// resolve fine while every KMP/iOS consumer breaks. Fail loudly instead.
val requireAppleHostForRemotePublish by tasks.registering {
    group = "verification"
    description = "Fails remote publishing on hosts that cannot build the iOS targets."

    doLast {
        if (!hostIsMac) {
            throw GradleException(
                "Remote publishing must run on macOS so the iOS variants are included; " +
                    "publishing from this host would ship incomplete module metadata.",
            )
        }
        if (rehearsalAllowMissingAndroidNativeLibs.get()) {
            throw GradleException(
                "idkit.rehearsal.allowMissingAndroidNativeLibs is a CI rehearsal flag for " +
                    "publishToMavenLocal only; remote publishing must include the Android native libraries.",
            )
        }
    }
}

kotlin {
    jvmToolchain(17)
    explicitApi()

    androidTarget {
        publishLibraryVariants("release")
    }

    val iosTargets = listOf(
        iosArm64() to "aarch64-apple-ios",
        iosSimulatorArm64() to "aarch64-apple-ios-sim",
        iosX64() to "x86_64-apple-ios",
    )
    iosTargets.forEach { (target, rustTriple) ->
        target.compilations.getByName("main").cinterops.create("idkit_kmp") {
            defFile(project.file("src/nativeInterop/cinterop/idkit_kmp.def"))
            includeDirs(repoRoot.resolve("rust/kmp-ffi/include"))
            extraOpts("-libraryPath", repoRoot.resolve("target/$rustTriple/release").absolutePath)
        }
    }

    sourceSets {
        commonMain {
            kotlin.srcDir(generateVersionFile)
            dependencies {
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2")
                implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.9.0")
            }
        }
        commonTest {
            dependencies {
                implementation(kotlin("test"))
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-test:1.10.2")
            }
        }
        androidMain {
            dependencies {
                implementation("net.java.dev.jna:jna:5.14.0@aar")
            }
        }
        getByName("androidUnitTest") {
            dependencies {
                // The @aar variant has no host libjnidispatch; unit tests run on
                // the host JVM and need the plain jar.
                implementation("net.java.dev.jna:jna:5.14.0")
            }
        }
    }
}

android {
    namespace = "com.worldcoin.idkit"
    compileSdk = 35

    defaultConfig {
        minSdk = 23
    }

    // KMP does not remap jniLibs to androidMain automatically; without this the
    // AAR would silently ship no native libraries and fail only at runtime.
    sourceSets["main"].jniLibs.srcDir("src/androidMain/jniLibs")

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    testOptions {
        unitTests.all { test ->
            // Host JVM tests load the host dylib built by scripts/build-kotlin.sh.
            test.jvmArgs("-Djna.library.path=${repoRoot.resolve("target/release").canonicalPath}")
        }
    }
}

mavenPublishing {
    configure(
        com.vanniktech.maven.publish.KotlinMultiplatform(
            javadocJar = com.vanniktech.maven.publish.JavadocJar.Empty(),
            sourcesJar = true,
            androidVariantsToPublish = listOf("release"),
        ),
    )
    coordinates(libraryGroup, libraryArtifactId, libraryVersion)

    pom {
        name.set("IDKit Kotlin")
        description.set("World ID SDK for Kotlin Multiplatform (Android + iOS), backed by the Rust core")
        url.set("https://github.com/worldcoin/idkit")
        licenses {
            license {
                name.set("MIT License")
                url.set("https://opensource.org/licenses/MIT")
            }
        }
        developers {
            developer {
                id.set("worldcoin")
                name.set("World Contributors")
            }
        }
        scm {
            url.set("https://github.com/worldcoin/idkit")
            connection.set("scm:git:git://github.com/worldcoin/idkit.git")
            developerConnection.set("scm:git:ssh://git@github.com/worldcoin/idkit.git")
        }
    }

    if (enableMavenCentralPublishing.get()) {
        publishToMavenCentral()
        signAllPublications()
    }
}

publishing {
    repositories {
        maven {
            name = "githubPackages"
            url = uri("https://maven.pkg.github.com/worldcoin/idkit")
            credentials {
                username = System.getenv("GITHUB_ACTOR") ?: System.getenv("GITHUB_USER")
                password = System.getenv("GITHUB_TOKEN")
            }
        }
    }
}

tasks.withType(PublishToMavenRepository::class.java).configureEach {
    dependsOn(verifyKmpNativeLibraries)
    dependsOn(requireAppleHostForRemotePublish)
}
tasks.withType(PublishToMavenLocal::class.java).configureEach {
    dependsOn(verifyKmpNativeLibraries)
}
