import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { describe, it, expect } from "vitest";
import fc from "fast-check";
import {
  fixedCases,
  config,
  context,
  response,
  item,
  NOW,
  REQUEST_ID,
  type OracleCase,
} from "./cases";
import {
  assertConformanceRejection,
  classifyConformanceError,
  dispatch,
} from "./dispatch";
import { CREDENTIAL_SCHEMA_IDS, APP_ERROR_CODES } from "../protocol";
import type { CredentialType, IDKitErrorCode, Preset } from "../types/protocol";
import { IDKitErrorCodes } from "../index";
import type { PublicContractChecks } from "./public-contract";

type OracleOutput =
  | { ok: true; value: any }
  | { ok: false; error: { kind: string; message: string } };
type Fixture = OracleCase & { expected: OracleOutput };
const fixtureUrl = new URL("./fixtures.json", import.meta.url);
const manifestUrl = new URL("./manifest.generated.ts", import.meta.url);
const binary = process.env.IDKIT_RUST_ORACLE;
function rust(inputs: Record<string, any>[]): OracleOutput[] {
  if (!binary)
    throw new Error("IDKIT_RUST_ORACLE is required for live conformance");
  const run = spawnSync(binary, [], {
    input: inputs.map((input) => JSON.stringify(input)).join("\n") + "\n",
    encoding: "utf8",
    maxBuffer: 32 * 1024 * 1024,
  });
  if (run.error) throw run.error;
  if (run.status !== 0)
    throw new Error(run.stderr || `Rust runner exited ${run.status}`);
  const results = run.stdout
    .trim()
    .split("\n")
    .map((line) => JSON.parse(line));
  expect(results).toHaveLength(inputs.length);
  return results;
}

if (process.env.IDKIT_CONFORMANCE_UPDATE === "1") {
  const outputs = rust(fixedCases.map((test) => test.input));
  // Refuse to replace the retained baseline with results JS cannot reproduce.
  // Native behavior changes still require an explicit update and diff review.
  fixedCases.forEach((test, i) => compare(test, outputs[i]!));
  const manifest = rust([{ op: "manifest" }])[0]!;
  if (!manifest.ok) throw new Error(manifest.error.message);
  writeFileSync(
    fixtureUrl,
    JSON.stringify(
      {
        format_version: 1,
        cases: fixedCases.map((test, i) => ({ ...test, expected: outputs[i] })),
      },
      null,
      2,
    ) + "\n",
  );
  writeFileSync(
    manifestUrl,
    `// Generated by the native Rust runner; update deliberately with IDKIT_CONFORMANCE_UPDATE=1.\nexport const manifest = ${JSON.stringify(manifest.value, null, 2)} as const;\n`,
  );
}
if (!existsSync(fixtureUrl))
  throw new Error(
    "Missing conformance corpus. Run IDKIT_CONFORMANCE_UPDATE=1 pnpm test:conformance.",
  );
const fixtures: Fixture[] = JSON.parse(readFileSync(fixtureUrl, "utf8")).cases;

function compare(test: OracleCase, expected: OracleOutput): void {
  if (expected.ok) {
    expect(dispatch(test.input), test.name).toEqual(expected.value);
    return;
  }
  let rejected = false;
  let error: unknown;
  try {
    dispatch(test.input);
  } catch (caught) {
    rejected = true;
    error = caught;
  }
  expect(rejected, `${test.name}: Rust rejects (${expected.error.kind})`).toBe(
    true,
  );
  expect(
    () => assertConformanceRejection(test.input.op, expected.error, error),
    test.name,
  ).not.toThrow();
}

describe("conformance rejection classifier", () => {
  it("permits only the documented serde boundaries and identical app error codes", () => {
    const jsonError = {
      kind: "json_error",
      message: "JSON error: malformed typed DTO",
    };
    expect(() =>
      assertConformanceRejection(
        "compile",
        jsonError,
        new Error("Invalid configuration: invalid field"),
      ),
    ).not.toThrow();
    expect(() =>
      assertConformanceRejection(
        "poll",
        jsonError,
        new Error("unexpected_response"),
      ),
    ).not.toThrow();
    expect(() =>
      assertConformanceRejection(
        "decrypt",
        jsonError,
        new Error("unexpected_response"),
      ),
    ).toThrow();
    expect(() =>
      assertConformanceRejection(
        "compile",
        jsonError,
        new TypeError("Invalid configuration: accidental undefined access"),
      ),
    ).toThrow();
    expect(() =>
      assertConformanceRejection(
        "proof_response",
        { kind: "app_error", message: "App error: UserRejected" },
        new Error("user_rejected"),
      ),
    ).not.toThrow();
    expect(() =>
      assertConformanceRejection(
        "proof_response",
        { kind: "app_error", message: "App error: UserRejected" },
        new Error("generic_error"),
      ),
    ).toThrow();
  });
  it("does not accept programming errors or a missing operation adapter", () => {
    expect(
      classifyConformanceError(
        new TypeError("Invalid configuration: accidental undefined access"),
      ),
    ).toBeUndefined();
    expect(
      classifyConformanceError(new ReferenceError("missing dependency")),
    ).toBeUndefined();
    expect(
      classifyConformanceError(
        new Error("No JS conformance operation missing"),
      ),
    ).toBeUndefined();
    expect(
      classifyConformanceError(new Error("unreviewed dependency failure")),
    ).toBeUndefined();
    expect(classifyConformanceError("unexpected_response")).toBeUndefined();
  });
  it("distinguishes validation, wire, authentication, encoding, and app failures", () => {
    expect(
      classifyConformanceError(
        new Error("Invalid configuration: Invalid nonce format"),
      )?.kind,
    ).toBe("invalid_configuration");
    expect(
      classifyConformanceError(new Error("unexpected_response"))?.kind,
    ).toBe("unexpected_response");
    expect(
      classifyConformanceError(new Error("aes/gcm: invalid ghash tag"))?.kind,
    ).toBe("crypto_error");
    expect(
      classifyConformanceError(new Error("Non-zero padding: 16"))?.kind,
    ).toBe("base64_error");
    expect(
      classifyConformanceError(new Error("utf8: invalid source encoding"))
        ?.kind,
    ).toBe("json_error");
    expect(classifyConformanceError(new Error("user_rejected"))).toEqual({
      kind: "app_error",
      appCode: "user_rejected",
    });
    try {
      JSON.parse("{");
    } catch (error) {
      expect(classifyConformanceError(error)?.kind).toBe("json_error");
    }
  });
});

describe("Rust compatibility fixtures", () => {
  it("covers the checked-in corpus inputs without silently dropping cases", () => {
    expect(fixtures.map(({ name, input }) => ({ name, input }))).toEqual(
      fixedCases,
    );
  });
  for (const test of fixtures)
    it(test.name, () => compare(test, test.expected));

  it("matches the Rust-derived enum and schema manifest", async () => {
    const { manifest } = await import("./manifest.generated");
    expect(CREDENTIAL_SCHEMA_IDS).toEqual(manifest.credentials);
    expect([...APP_ERROR_CODES].sort()).toEqual(
      [...manifest.error_codes].sort(),
    );
    expect(Object.values(IDKitErrorCodes).sort()).toEqual(
      [
        ...manifest.error_codes,
        "invalid_rp_id_format",
        "timeout",
        "cancelled",
      ].sort(),
    );
    // These witnesses cannot type-check after an incompatible change in either
    // the native manifest or the public declarations.
    const declarationsMatch: PublicContractChecks = [
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
    ];
    expect(declarationsMatch.every(Boolean)).toBe(true);
    expect(manifest.response_shapes).toHaveLength(5);
    expect(manifest.response_shapes_full).toHaveLength(5);
    const presetTags: Record<Preset["type"], true> = {
      OrbLegacy: true,
      SecureDocumentLegacy: true,
      DocumentLegacy: true,
      DeviceLegacy: true,
      SelfieCheckLegacy: true,
      SelfieCheck: true,
      ProofOfHuman: true,
      Passport: true,
      Mnc: true,
      IdentityCheck: true,
    };
    expect(Object.keys(presetTags).sort()).toEqual(
      manifest.presets.map((p) => p.type).sort(),
    );
    type Equal<A, B> = [A] extends [B]
      ? [B] extends [A]
        ? true
        : never
      : never;
    const credentialsMatch: Equal<
      CredentialType,
      keyof typeof manifest.credentials
    > = true;
    const errorsMatch: Equal<
      IDKitErrorCode,
      (typeof manifest.error_codes)[number]
    > = true;
    expect(credentialsMatch && errorsMatch).toBe(true);
  });
});

describe.skipIf(!binary)("live native Rust differential checks", () => {
  it("preserves the former JS adapter safe-integer boundary without rounding native u64 values", () => {
    // The former WASM adapter used Serializer::new().serialize_maps_as_objects(true).
    // serde-wasm-bindgen 0.6.5 defaults serialize_large_number_types_as_bigints
    // to false and serialize_u64 rejects values above Number.MAX_SAFE_INTEGER.
    // Native Rust can represent those values; that broader domain is explicit.
    const wide = 9_007_199_254_740_992;
    const input = {
      op: "response",
      context,
      response: { ...response, responses: [{ ...item, expires_at_min: wide }] },
    };
    const native = rust([input])[0]!;
    expect(native.ok).toBe(true);
    if (native.ok) {
      expect(native.value.result.responses[0].expires_at_min).toEqual({
        $u64: "9007199254740992",
      });
    }
    expect(() => dispatch(input)).toThrow(/^unexpected_response$/);
    const safe = {
      ...input,
      response: {
        ...response,
        responses: [{ ...item, expires_at_min: Number.MAX_SAFE_INTEGER }],
      },
    };
    compare(
      { name: "maximum safe integer response", input: safe },
      rust([safe])[0]!,
    );
  });
  it("keeps current Rust behavior consistent with retained fixtures", () => {
    const current = rust(fixtures.map((test) => test.input));
    fixtures.forEach((test, i) => {
      // Diagnostics may change without altering the contract; failure class may not.
      const actual = current[i]!;
      if (test.expected.ok) expect(actual, test.name).toEqual(test.expected);
      else {
        expect(actual.ok, test.name).toBe(false);
        if (!actual.ok)
          expect(actual.error.kind, test.name).toEqual(
            test.expected.error.kind,
          );
      }
      compare(test, actual);
    });
  });
  it("checks generated inputs with reproducible seeds and shrinking", () => {
    const leaf = fc.record({
      type: fc.constantFrom("proof_of_human", "selfie", "passport", "mnc"),
      signal: fc.oneof(
        fc.string(),
        fc.constantFrom("0x", "0x00", "🌍", "0x123"),
      ),
      expires_at_min: fc.nat({ max: 2_000_000_000 }),
    });
    const tree = fc
      .tuple(
        fc.constantFrom("any", "all", "enumerate"),
        fc.array(leaf, { minLength: 1, maxLength: 5 }),
      )
      .map(([kind, items]) => ({ [kind]: items }));
    const scenario = fc.record({
      constraints: fc.oneof(leaf, tree),
      kind: fc.constantFrom("request", "create_session"),
      native: fc.boolean(),
    });
    fc.assert(
      fc.property(scenario, (value) => {
        const input = {
          op: "compile",
          config: { ...config, kind: value.kind },
          selection: { constraints: value.constraints },
          native: value.native,
          request_id: REQUEST_ID,
          now: NOW,
        };
        compare({ name: JSON.stringify(value), input }, rust([input])[0]!);
      }),
      { seed: 20260912, numRuns: 150 },
    );
    fc.assert(
      fc.property(fc.uint8Array({ maxLength: 256 }), (bytes) => {
        const input = {
          op: "encrypt",
          key_hex: "01".repeat(32),
          iv_hex: "02".repeat(12),
          plaintext_hex: Buffer.from(bytes).toString("hex"),
        };
        const expected = rust([input])[0]!;
        compare({ name: "generated AES", input }, expected);
        if (expected.ok) {
          const decryptInput = {
            op: "decrypt",
            key_hex: input.key_hex,
            iv_hex: input.iv_hex,
            ciphertext_hex: expected.value.ciphertext_hex,
          };
          compare(
            { name: "cross-decrypt", input: decryptInput },
            rust([decryptInput])[0]!,
          );
        }
      }),
      { seed: 20260912, numRuns: 50 },
    );
  });
  it("regenerates the actual Rust type manifest and server signature fixtures", async () => {
    const { manifest } = await import("./manifest.generated");
    expect(rust([{ op: "manifest" }])[0]).toEqual({
      ok: true,
      value: manifest,
    });
    const server = JSON.parse(
      readFileSync(
        new URL(
          "../../../server/src/__tests__/fixtures/rust-signing.json",
          import.meta.url,
        ),
        "utf8",
      ),
    );
    const current = rust(server.cases.map((test: any) => test.request));
    server.cases.forEach((test: any, i: number) =>
      expect(current[i], test.name).toEqual(test.response),
    );
  });
});
